name: CMake

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Configure Solver
    run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

  - name: Build Solver
    run: cmake --build ${{github.workspace}}/build

  - name: Create Artifact
    run: |
      mkdir ${{github.workspace}}/artifacts
      cp ${{github.workspace}}/build/solver ${{github.workspace}}/artifacts/solver
      echo "Artifact created at ${{github.workspace}}/artifacts/solver"
